# Generated by Django 5.1.6 on 2025-03-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_transaction_category'),
        ('backend', 'new_account_fields'),
    ]

    operations = [
    ]
