# Generated by Django 5.1.6 on 2025-09-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_tdtransaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auto_categorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('contains', 'Description Contains'), ('exact', 'Exact Match'), ('amount_range', 'Amount Range'), ('recurring', 'Recurring Payment')], max_length=20)),
                ('pattern', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
