# Generated by Django 5.1.6 on 2025-09-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtransaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
