# Generated by Django 5.1.6 on 2025-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_transaction_auto_categorized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_backups', models.PositiveIntegerField(default=5, help_text='Maximum number of auto-backups to keep')),
                ('auto_backup_enabled', models.BooleanField(default=True, help_text='Enable automatic backups')),
                ('backup_frequency_hours', models.PositiveIntegerField(default=24, help_text='Hours between automatic backups')),
                ('last_backup', models.DateTimeField(blank=True, help_text='Last backup timestamp', null=True)),
                ('backup_location', models.CharField(default='backups/', help_text='Directory to store backups', max_length=500)),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('file_path', models.CharField(help_text='Path to backup file', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Size of backup file in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_compressed', models.BooleanField(default=True, help_text='Whether backup is compressed')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this backup')),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
