# Generated by Django 5.1.6 on 2025-09-16 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_backupsettings_databasebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='suggested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_transactions', to='backend.category'),
        ),
    ]
