# Generated by Django 5.1.6 on 2025-09-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_transaction_suggested_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2196F3', help_text='Hex color code for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rule Group',
                'verbose_name_plural': 'Rule Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='categorizationrule',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Categorization Rule', 'verbose_name_plural': 'Categorization Rules'},
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='Whether pattern matching should be case sensitive'),
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Additional conditions for combined rules'),
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='created_by',
            field=models.CharField(default='system', help_text='Who created this rule', max_length=100),
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this rule does'),
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='last_matched',
            field=models.DateTimeField(blank=True, help_text='When this rule last matched a transaction', null=True),
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='match_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of transactions matched by this rule'),
        ),
        migrations.AlterField(
            model_name='categorizationrule',
            name='pattern',
            field=models.TextField(help_text='The pattern to match (keywords, regex, amount, etc.)'),
        ),
        migrations.AlterField(
            model_name='categorizationrule',
            name='priority',
            field=models.IntegerField(default=1, help_text='Higher number = higher priority'),
        ),
        migrations.AlterField(
            model_name='categorizationrule',
            name='rule_type',
            field=models.CharField(choices=[('keyword', 'Keyword Match'), ('contains', 'Description Contains'), ('exact', 'Exact Match'), ('regex', 'Regular Expression'), ('amount_range', 'Amount Range'), ('amount_exact', 'Exact Amount'), ('amount_greater', 'Amount Greater Than'), ('amount_less', 'Amount Less Than'), ('recurring', 'Recurring Payment'), ('merchant', 'Merchant Name'), ('date_range', 'Date Range'), ('day_of_week', 'Day of Week'), ('combined', 'Combined Conditions')], max_length=20),
        ),
        migrations.CreateModel(
            name='RuleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('was_applied', models.BooleanField(default=True, help_text='Whether this rule was actually applied to categorize the transaction')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='backend.categorizationrule')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transaction')),
            ],
            options={
                'verbose_name': 'Rule Usage',
                'verbose_name_plural': 'Rule Usage Records',
                'ordering': ['-matched_at'],
            },
        ),
    ]
