# Generated by Django 5.1.6 on 2025-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20250917_1639'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='backend_category_name_parent_uniq',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
