# Generated by Django 5.1.6 on 2025-09-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_category_backend_category_name_parent_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScotiabankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('sub_description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'scotiabank',
            },
        ),
    ]
